---
networks:
  gamutrf:
services:
  torchserve:
    restart: always
    image: anarkiwi/torchserve:v0.0.2
    healthcheck:
      start_period: 120s
    networks:
      - gamutrf
    ports:
      - '8080:8080'
      - '8081:8081'
    volumes:
      - '${VOL_PREFIX}/model_store:/model_store'
      - '/root/.cache/pip:/root/.cache/pip'
    command:
      # --models torchsig_model=torchsig_model.mar
      # As of torchserve v11, you will need to add setuptools==69.5.1
      # to your requirements.txt when generating a MAR file
      # https://github.com/pytorch/serve/issues/3176
      - --disable-token-auth
      - --models model=model.mar
