# nosemgrep:github.workflows.config.dockerfile-source-not-pinned
FROM python:3.11-slim

WORKDIR /app

RUN pip3 install poetry==1.1.5
RUN pip3 install setuptools==68.0.0
COPY pyproject.toml .
RUN poetry config virtualenvs.create false
RUN poetry install

COPY mavlink-api.py .

# nosemgrep:github.workflows.config.missing-user
CMD ["python3", "mavlink-api.py"]
