name: buildx-extras

on:
  push:
    branches: main
    tags: 'v*'

jobs:
  buildx-mavlink-api:
    runs-on: ubuntu-latest
    environment:
      name: "release"
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Change for main
      id: change_version
      run: if [ "${{ steps.get_version.outputs.VERSION }}" == "main" ]; then echo ::set-output name=VERSION::latest; else echo ::set-output name=VERSION::${{ steps.get_version.outputs.VERSION }}; fi
    - name: Set up qemu
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
      if: github.repository == 'anarkiwi/gamutrf' && github.event_name == 'push'
    - name: Build and push platforms
      uses: docker/build-push-action@v6
      with:
        context: utils/mavlink-api
        file: utils/mavlink-api/Dockerfile.mavlink-api
        platforms: linux/amd64
        push: true
        tags: anarkiwi/gamutrf-mavlink-api:${{ steps.change_version.outputs.VERSION }}
      if: github.repository == 'anarkiwi/gamutrf' && github.event_name == 'push'
  buildx-airspyfm:
    runs-on: ubuntu-latest
    environment:
      name: "release"
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Change for main
      id: change_version
      run: if [ "${{ steps.get_version.outputs.VERSION }}" == "main" ]; then echo ::set-output name=VERSION::latest; else echo ::set-output name=VERSION::${{ steps.get_version.outputs.VERSION }}; fi
    - name: Set up qemu
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
      if: github.repository == 'anarkiwi/gamutrf' && github.event_name == 'push'
    - name: Build and push platforms
      uses: docker/build-push-action@v6
      with:
        context: docker
        file: docker/Dockerfile.airspyfm
        platforms: linux/amd64,linux/arm64
        push: true
        tags: anarkiwi/gamutrf-airspyfm:${{ steps.change_version.outputs.VERSION }}
      if: github.repository == 'anarkiwi/gamutrf' && github.event_name == 'push'
